/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoomiButton {
        /**
          * The type of button, primary or secondary
         */
        "flavor": string;
    }
}
declare global {
    interface HTMLBoomiButtonElement extends Components.BoomiButton, HTMLStencilElement {
    }
    var HTMLBoomiButtonElement: {
        prototype: HTMLBoomiButtonElement;
        new (): HTMLBoomiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "boomi-button": HTMLBoomiButtonElement;
    }
}
declare namespace LocalJSX {
    interface BoomiButton {
        /**
          * The type of button, primary or secondary
         */
        "flavor"?: string;
    }
    interface IntrinsicElements {
        "boomi-button": BoomiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "boomi-button": LocalJSX.BoomiButton & JSXBase.HTMLAttributes<HTMLBoomiButtonElement>;
        }
    }
}
